FROM buildkite/puppeteer:v1.15.0
RUN apt-get update && apt-get install -y git-core
RUN yarn global add nodemon
WORKDIR /code/
COPY package.json yarn.lock ./
RUN yarn
COPY . .
EXPOSE 3000
CMD nodemon index.js
