version: '2'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code/
      - /code/node_modules/
    env_file: .env
    ports:
      - 7712:3000
  redis:
      image: redis:5.0.6-alpine
