version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13.10-stretch
    steps:
      - checkout
      - run:
        name: setup env
        command: |
          echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
          echo 'export IMAGE_NAME=gather_api' >> $BASH_ENV
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-deps
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build and publish docker image
          command: |
            docker build -t remotecong/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push remotecong/$IMAGE_NAME:$TAG

